spring.datasource.url=jdbc:postgresql://ep-mute-wildflower-a14j2bvd-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=false

spring.security.oauth2.client.registration.google.client-id=654797097402-q24pggjlgurft26nuhhmoe38p77vp7ic.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# Frontend URL for CORS (comma separated if multiple)
app.frontend.url=<add_url_here>