server.port=${PORT:8080}
spring.application.name=goat-watches

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

upload.dir=${UPLOAD_DIR:/tmp/uploads}
admin.token=${ADMIN_TOKEN:changeme}

# Database Configuration (Default/Local - Direct Connection)
spring.datasource.url=jdbc:postgresql://ep-mute-wildflower-a14j2bvd-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# session mgmt
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.timeout=1h

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Seeder Configuration
app.seeder.enabled=false
app.seeder.allowed-brands=Rolex,Omega,Tissot


# logging
logging.level.org.springframework.security=DEBUG

# Frontend URL for CORS (comma separated if multiple)
app.frontend.url=http://localhost:5000


# Email Configuration (mailtrap sandbox Example)
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=34c7350eddbdc4
#spring.mail.password=${MAIL_SECRET}
#spring.mail.properties.mail.smtp.auth=false
#spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=apexdial1@gmail.com
spring.mail.password=${MAIL_SECRET}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OAuth2 Configuration
# Google
spring.security.oauth2.client.registration.google.client-id=654797097402-q24pggjlgurft26nuhhmoe38p77vp7ic.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email,openid
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
