spring.security.oauth2.client.registration.google.client-id=<create_client_id>
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# Frontend URL for CORS (comma separated if multiple)
app.frontend.url=https://apexdial.com