
spring.security.oauth2.client.registration.google.client-id=654797097402-q24pggjlgurft26nuhhmoe38p77vp7ic.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# Frontend URL for CORS (comma separated if multiple)
app.frontend.url=http://localhost:5000